def count_nt(s):
    nt_counts = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
    for nt in s:
        if nt in nt_counts:
            nt_counts[nt] += 1
    return nt_counts['A'], nt_counts['C'], nt_counts['G'], nt_counts['T']

#s = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC"
s = "TGGTTATCCCGCCTCCGAAGCTAAACTCCTGTCCAGGAATATCTTGTTTGTAATAAAGCTACTAATTAGTCCGAGGCCTATCAGTCTGTGGCAGGCAAACTTCTTACAGATTCGAGGGCCATAGAGCAGTTTCCGATACAACCCTTGATGCTTCAGAATCAGGCGCGTCACCGAAGCTGTGTAGCGGCGACATAAACCTGGCCAATATACGTGGAGCCACAGTACGGGAAATAGTGACAGAGACGGCAGGAAGTCTCCTTAAAGTTTGAGAGCGGGACCAACGTGCGAGTCACTAGTTTGGGGGGATATGTGGGATGATGGGCCGACGGTGCGGAACTCCGTTGACTAGGGAGGAGAGAATGACTTTACGCACGTCTTGACGATGCCTCTGAGATGCTTGTTGGCCCCGTGAGACCGGAACGCCATGTCGCGCATCGCCAGAGCTGCATATTGTAGAGCTAATACCATCACCTTAATCAAGTCTCTTGAACGCTATGGAGTAGTATGACTTTCCTTCGGACTAAGCATCCCGATGACTTAGACTGAACATCAAACGTCAAACGTCCCAAACATCAACAGCAAGTACCCTCGTGCGGAAGGCCTTATCCATCGTTGAGCGCAGGTTCTGATAACACCTGATTGTGAGCAGCAAGGTGCCAGGCCAACCGATTCTCTATTTCGCATCTAGACGGGCTCCCACTAACTGCTGATACGACGCGGCACCGTCAGTTTCTATCTTAACTGCTAGTATCCTATGAATGATTCTTAGTTAGTGATATTGACGACAAGATGGACCACTCACCGGCCGGGACTCATGATTGTCCCAATCCAATAAATATCAACCAGAGTACCACTGGCGCCCAACATATCTGTCCACCGACAGTCCTTTGCTTAGAGGTAGGCCCGGGCGTGTCCTGCGGAGTTTGATTTTA"
a, c, g, t = count_nt(s)
print(a, c, g, t)

