def find_substring(s, t):
    positions = []
    for i in range(len(s) - len(t) + 1):
        if s[i:i+len(t)] == t:
            positions.append(i+1)
    return " ".join(str(pos) for pos in positions)

s = "AATGTAGTGCTAGTACTTGGCACTATAACTACAAGTAGTGCAACCTGTAGTGCGTAGTGCGTAGTGCCGTAGTGCCCGGTAGTGCTGTAGTGCCCGGACGTAGTGCGTAGTGCTCCGTAGTGCCGTAGTGCAAGTAGTGCGTAGTGCTGTAGTGCTGTAGTGCCGAATGTAGTGCACGTAGTGCTCGTCTTCCCAGAGTAGTGCTAGTAGTGCGGTAGTGCTCTGTAGTGCATTCAGGTAGTGCCCTGTGTAGTGCGTGTAGTGCATTTGTAGTGCGTAGTGCAACCCGGACTAGTAGTGCTGTAGTGCAGGTAGTGCTAACCACCTCGGTAGTGCAGTAGTGCCATAGTAGTGCCCCTATGTAGTGCTCCCTGAGTAGTGCAGTAGTGCGTAGTGCGTAGTGCTTATGTGTAGTGCGGTAGTGCAGTAGTGCACGTAGTGCGTAGTGCCGGTGCTTGTAGTGCCAGTAGTGCGTAGTGCAAGTGTGCAGTAGTGCCATGTAGTGCCCTCAGAGTGTAGTGCTAACGTAGTGCGTAGTGCGTAGTGCTAGTAGTGCGGGAGTAGTGCGTAGTGCTGTAGTGCGTAGTGCGTAGTGCGTAGTGCGTAGTGCCTAGTAGTGCGGAAGTAGTGCCGGTAGTGCGTTGTAGTGCTGCTAAGGTGTTGTAGTGCCGTAGTGCTAGTAGTGCCTGGTTGAGTAGTGCGTAGTGCATATCGTAGTGCAAGTAGTGCAAGACATTAGTAGTGCGTCCGTAGTGCCGTAGTGCATGTAGTGCGTAGTGCGTAGTGCGTAGTGCGAGTAGTGCGTAGTGCGTAGTGCAGTAGTGCCCTCGTAGTGCGCAACCGGTAGTGCCGGGTAGTGCGTACGTAGTGCCGTTGTAGTGCAGTAGTGCGAAACACGTA"
t = "GTAGTGCGT"
print(find_substring(s, t))
# Output: "2 4 10"