


codonNumbers = {
'F' : 2,
'L' : 6,
'S' : 6,
'Y' : 2,
'C' : 2,
'W' : 1,
'P' : 4,
'H' : 2,
'Q' : 2,
'R' : 6,
'I' : 3,
'M' : 1,
'T' : 4,
'N' : 2,
'K' : 2,
'V' : 4,
'A' : 4,
'D' : 2,
'E' : 2,
'G' : 4,
'Stop': 3
}

#i = 0;
#for value in codonNumbers.values():
#    i += value;
#print(i) # should == 64

inputString = 'MIEPDRTQLDMVPPQSSRVECCFDEIYRLAFSTGRFIACDGAVALMPGWKYWTDNDERNVGLKIPFLFFMYSGRTFWVDICGLGACMVAQVKAEYWLQSDVSQWCTKDRWKIEDNAERKNKMYQYQRPVRIMYVCLWNLQTNKMYWRACPMIFLDYYKFTLMFCQDAEANEFNKAVWSYCGAHVTYPSVVIMGKVWNTHDNELAMYCGHKTRDKVMWGCYHEVPNGEEYMVAPMVFQCIHPPCIGEKEPECEAFHVEHKYAYKNQPKLEKCQWMAPILQDITHMDWYTYVEYMYLGIQNLKACSTLVDEQEMGNRTMHMPQAFRFDTQCGMSPWSCYEGESPHSRHGTMEYEENILAAFFHHVSVSEMSCNHYKMGAMGSWGINQGFDFQLTHTPIEGSRKWQYFMWQHDQPSNRIKNLDHDSFRFILPFHVQFYTVPCYLPFQEWSRKTNKTNHTCKKLWCYFPHHMGSWQLRCQPPYKKWKRFYTIHPIHLTHHHLTLPKLSKLGMPDLYMNHYPGSDPYDKPYKYTTHIHDFQINTFTANKQVFCSNVTQCHSIGAFHQSHPLDSWAEMKQWSSFWHEIKMECTYNHRNNNCGKTEFLVAKFLRVMDVQTVDDCWYNGTNAYSKPVSAEMYFSGETWVSQPCMSKWYKYNVPEKIHCGHDMMSCYIDFNMHDGTYFWIKSYASTYTENHCHPCQGESKWAHQACWFEHNSPFSQHYNSHYDDWYTHIKLTMMRVKMGQDHWAYCHDMACRASGMRPTSQFKHTREMVFFYPSDCMVGYLIGPRIHQCQGQAYAMKRCRHEISGSFFLARARYIPYYQMGWVHRQKSQIWHPSENVMPIATPDLGSIEECCQMMGIAWEVDKTSAGSMPAPVERDMGHCSFNHRRAKDISFAMKLESAMIGCSMTYDASIMGWASVWCFTIYTRGCTVAGCEKQKDKYGQNYEVSCIRSFELDEMCEGHYLCLSYWNAMSISQSEVKADVAYVSPRAEGDEAMAIHH'
possibleCombos = 1

for char in inputString:
    #print(codonNumbers[char])
    possibleCombos *= codonNumbers[char]

possibleCombos *= codonNumbers['Stop']

print( possibleCombos % 1000000 )



