

input = "CAATGCCTCTCAGTGAGCCGTACTGCTAACTCCAATTATCCCCAAGACGTAAATGCAACCGTAAACCATCGCCTGCGTCATAGACCGTATTGTTAGGATCTATGACTAATGCGTCCGGTGTCTCCTTCTTAATAAAGTCCCCGTGCACGATAAGCGTAGTGTAGACGGCGACTGGGCTCTAACGGATTTGCGCCATCCATATGTTACTGGGGAGCTTACGTATAGTCCGGTAGATACACAGGGTGTTATTGTCCCAATCACTGATGCCGGTTTTCATCGGATTATTCGTCAATGCAACTACGGCTCTGGCCCAATAGTCGGAAACCTGTGGGTCAAACCAGGGTTAACCGCGACGCTTACCTGATGTATGCGGGAAACGAATTGAAATAACCCCTTATTTCTGCGTGTACTGTTGGATAAAAGATCCCCCTCGTACCGACGTTGTTATCCGGAGGTAAGCACGGCACGGACGGGTCACCCCGACACGGAATAATTGCTCCATTCGGCCTGCCTGACTTCCCACAAACGACGATCGACTTTACAACTGTTTATTTGGTCCTTTGGAGGAGTGATCACTTACACTATACGGACGATAAAATTGGTCAATCCACGGAAGCTAGTTAGTAAAGAGTAAATAAAGCCAGCTCAACTACACAACCACAGTACCGACTACTGCGATGACAGGCTGGTACTAACAGGCATCGTCTTTTCCGCGGCTTCGTTATTCATAGTCCATCCCTCTCCTGAACTCGACTGTAAGCCGCTACCCTTACAACATAATCGCGGAAGTGGGATCAGCTCCGTAAGTAGTTGTCACGGTTACCGGTGCGCCTTAGGTCGTCCTCTCCATAGTTTTGACGTGCTGGTGCGCCCGTGCTAATCTTGGCTAAAATATTGCCACGGTATGGCAAATGTCCAGAAGATGAAAATACGACCGCCTTATTTTATGTCTATTGAACCTTA"

complement = ""

def reverseString(x):
  return x[::-1]


for element in range(0, len(input)):
    if input[element] == 'T':
        complement += 'A'
    if input[element] == 'A':
        complement += 'T'
    if input[element] == 'C':
        complement += 'G'
    if input[element] == 'G':
        complement += 'C'


revComp = reverseString(complement);

print(revComp)